services:
  integration-test:
    build:
      context: ../../../
      dockerfile: ./build/package/integration_test/Dockerfile
    environment:
      - TEST_OPENAI_KEY=${IDN_REMOTE_ENTRY_OPENAI_KEY}
      - TEST_WHATSAPP_API_USER=${GHAZLABS_WA_SERVER_USER}
      - TEST_WHATSAPP_API_PASS=${GHAZLABS_WA_SERVER_PASS}
      - TEST_WHATSAPP_RECIPIENT_ID=120363390036841640@newsletter
    entrypoint: "go test -timeout=1m30s -short ./..."
    volumes:
      - ../../../internal:/go/src/github.com/ghazlabs/idn-remote-entry/internal