services:
  integration-test:
    build:
      context: ../../../
      dockerfile: ./build/package/integration_test/Dockerfile
    environment:
      - TEST_OPENAI_KEY=${IDN_REMOTE_ENTRY_OPENAI_KEY}
      - TEST_WHATSAPP_API_USER=${GHAZLABS_WA_SERVER_USER}
      - TEST_WHATSAPP_API_PASS=${GHAZLABS_WA_SERVER_PASS}
      - TEST_WHATSAPP_RECIPIENT_IDS=120363390036841640@newsletter,120363376193442839@g.us
      - TEST_WHATSAPP_API_BASE_URL=${GHAZLABS_WA_SERVER_URL}
      - TEST_NOTION_DATABASE_ID=${IDN_REMOTE_ENTRY_NOTION_DATABASE_ID_DEV} # this is dev table
      - TEST_NOTION_TOKEN=${IDN_REMOTE_ENTRY_NOTION_TOKEN}
    entrypoint: "go test -timeout=3m ./..."
    volumes:
      - ../../../internal:/go/src/github.com/ghazlabs/idn-remote-entry/internal