services:
  rabbitmq:
    image: rabbitmq:4.0.5-management
    ports:
      - "15672:15672"  # Management web UI
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  mysql:
    image: bitnami/mysql:8.0
    healthcheck:
      test: "mysql --user=root --password=test1234 --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
    ports:
      - 8306:3306
    volumes:
      - ../../../docs/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    environment:
      - MYSQL_ROOT_PASSWORD=test1234
      - MYSQL_DATABASE=idnremote

  mailpit:
    image: axllent/mailpit:v1.23
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP port
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1

  integration-test:
    build:
      context: ../../../
      dockerfile: ./build/package/integration_test/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      mailpit:
        condition: service_started
    environment:
      - TEST_SMTP_HOST=mailpit
      - TEST_SMTP_PORT=1025
      - TEST_RABBITMQ_CONN=amqp://guest:guest@rabbitmq:5672/
      - TEST_RABBITMQ_WA_QUEUE_NAME=wa_queue
      - TEST_RABBITMQ_VACANCY_QUEUE_NAME=vacancy_queue
      - TEST_MYSQL_DSN=root:test1234@tcp(mysql:3306)/idnremote?timeout=5s
    entrypoint: "go test -timeout=3m -short ./..."
    volumes:
      - ../../../internal:/go/src/github.com/ghazlabs/idn-remote-entry/internal
