services:
  server:
    build:
      context: ../../../
      dockerfile: ./build/package/server/Dockerfile
    environment:
      - NOTION_DATABASE_ID=${IDN_REMOTE_ENTRY_NOTION_DATABASE_ID_DEV} # this is dev table
      - NOTION_TOKEN=${IDN_REMOTE_ENTRY_NOTION_TOKEN}
      - OPENAI_KEY=${IDN_REMOTE_ENTRY_OPENAI_KEY}
      - LISTEN_PORT=9864
      - CLIENT_API_KEY=d2e97dca-1131-4344-af0a-b3406e7ecb06
      - WHATSAPP_API_USER=${GHAZLABS_WA_SERVER_USER}
      - WHATSAPP_API_PASS=${GHAZLABS_WA_SERVER_PASS}
      - WHATSAPP_RECIPIENT_IDS=120363390036841640@newsletter,120363376193442839@g.us # this is dev channel & dev community
    ports:
      - "9864:9864"
