services:
  server:
    build:
      context: ../../../
      dockerfile: ./build/package/server/Dockerfile
    environment:
      - NOTION_DATABASE_ID=1513500463578022840df032e88f5a19 # this is dev table
      - NOTION_TOKEN=${IDN_REMOTE_ENTRY_NOTION_TOKEN}
      - OPENAI_KEY=${IDN_REMOTE_ENTRY_OPENAI_KEY}
      - LISTEN_PORT=9864
      - CLIENT_API_KEY=d2e97dca-1131-4344-af0a-b3406e7ecb06
    ports:
      - "9864:9864"