services:
  server:
    build:
      context: ../../../
      dockerfile: ./build/package/server/Dockerfile
    environment:
      - NOTION_DATABASE_ID=${IDN_REMOTE_ENTRY_NOTION_DATABASE_ID_PROD} # this is prod table
      - NOTION_TOKEN=${IDN_REMOTE_ENTRY_NOTION_TOKEN}
      - OPENAI_KEY=${IDN_REMOTE_ENTRY_OPENAI_KEY}
      - LISTEN_PORT=9864
      - CLIENT_API_KEY=${IDN_REMOTE_ENTRY_CLIENT_API_KEY}
    ports:
      - "9864:9864"
