services:
  server:
    build:
      context: ../../../
      dockerfile: ./build/package/server/Dockerfile
    environment:
      - NOTION_DATABASE_ID=${IDN_REMOTE_ENTRY_NOTION_DATABASE_ID_PROD} # this is prod table
      - NOTION_TOKEN=${IDN_REMOTE_ENTRY_NOTION_TOKEN}
      - OPENAI_KEY=${IDN_REMOTE_ENTRY_OPENAI_KEY}
      - LISTEN_PORT=9864
      - CLIENT_API_KEY=${IDN_REMOTE_ENTRY_CLIENT_API_KEY}
      - WHATSAPP_API_USER=${GHAZLABS_WA_SERVER_USER}
      - WHATSAPP_API_PASS=${GHAZLABS_WA_SERVER_PASS}
      - WHATSAPP_RECIPIENT_IDS=${IDN_REMOTE_ENTRY_WHATSAPP_RECIPIENT_IDS_PROD} # this is prod channel & prod community
    ports:
      - "9864:9864"
