services:
  rabbitmq:
    image: rabbitmq:4.0.5-management
    ports:
      - "15672:15672"  # Management web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest 
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  server:
    build:
      context: ../../../
      dockerfile: ./build/package/server/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SERVER_DOMAIN=${IDN_REMOTE_ENTRY_SERVER_DOMAIN}
      - LISTEN_PORT=9864
      - CLIENT_API_KEY=${IDN_REMOTE_ENTRY_CLIENT_API_KEY}
      - RABBITMQ_CONN=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_VACANCY_QUEUE_NAME=vacancy_queue
      - APPROVED_SUBMITTER_EMAILS=${IDN_REMOTE_ENTRY_APPROVED_SUBMITTER_EMAILS}
      - ADMIN_EMAILS=${IDN_REMOTE_ENTRY_ADMIN_EMAILS}
      - SMTP_HOST=${IDN_REMOTE_ENTRY_SMTP_HOST}
      - SMTP_PORT=${IDN_REMOTE_ENTRY_SMTP_PORT}
      - SMTP_FROM=${IDN_REMOTE_ENTRY_SMTP_FROM}
      - SMTP_PASS=${IDN_REMOTE_ENTRY_SMTP_PASS}
      - APPROVAL_JWT_SECRET_KEY=${IDN_REMOTE_ENTRY_APPROVAL_JWT_SECRET_KEY}
    ports:
      - "9864:9864"

  vacancy-worker:
    build:
      context: ../../../
      dockerfile: ./build/package/vacancy-worker/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - NOTION_DATABASE_ID=${IDN_REMOTE_ENTRY_NOTION_DATABASE_ID_PROD} # this is prod table
      - NOTION_TOKEN=${IDN_REMOTE_ENTRY_NOTION_TOKEN}
      - OPENAI_KEY=${IDN_REMOTE_ENTRY_OPENAI_KEY}
      - RABBITMQ_CONN=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_WA_QUEUE_NAME=wa_queue
      - RABBITMQ_VACANCY_QUEUE_NAME=vacancy_queue

  notification-worker:
    build:
      context: ../../../
      dockerfile: ./build/package/notification-worker/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - WHATSAPP_API_USER=${GHAZLABS_WA_SERVER_USER}
      - WHATSAPP_API_PASS=${GHAZLABS_WA_SERVER_PASS}
      - WHATSAPP_API_BASE_URL=${GHAZLABS_WA_SERVER_URL}
      - WHATSAPP_RECIPIENT_IDS=${IDN_REMOTE_ENTRY_WHATSAPP_RECIPIENT_IDS_PROD} # this is prod channel & prod community
      - RABBITMQ_CONN=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_WA_QUEUE_NAME=wa_queue

volumes:
  rabbitmq_data: