name: Deploy

on:
  release:
    types: [released]
  # debug
  push:
    branches:
      - chore/deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: SSH and Run Commands on Remote Server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/go/src/github.com/ghazlabs/idn-remote-entry
            git checkout main
            git pull
            make deploy-ec2