name: Deploy

on:
  release:
    types: [released]
  # debug
  push:
    branches:
      - chore/deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: SSH and Run Commands on Remote Server
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -i private_key.pem ec2-user@54.151.247.236 <<EOF
            cd ~/go/src/github.com/ghazlabs/idn-remote-entry
            git checkout main
            git pull
            make deploy-ec2
          EOF

          rm -f private_key.pem